// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49uGHkrNM35Pp_w7NsWkB7vnLNwEJ8F8',
    appId: '1:53988516072:web:6548e06c136badbdd1e95d',
    messagingSenderId: '53988516072',
    projectId: 'liad-apps',
    authDomain: 'liad-apps.firebaseapp.com',
    storageBucket: 'liad-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2O2jYetFUjUi8IPUMrjDyx_cUZn42TA',
    appId: '1:53988516072:android:ff799e81119ce494d1e95d',
    messagingSenderId: '53988516072',
    projectId: 'liad-apps',
    storageBucket: 'liad-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhr7R9IfDkrGVVlLgPjiavXXSuK9rzNsY',
    appId: '1:53988516072:ios:e95767d80ef7079ad1e95d',
    messagingSenderId: '53988516072',
    projectId: 'liad-apps',
    storageBucket: 'liad-apps.firebasestorage.app',
    iosBundleId: 'com.example.liad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhr7R9IfDkrGVVlLgPjiavXXSuK9rzNsY',
    appId: '1:53988516072:ios:e95767d80ef7079ad1e95d',
    messagingSenderId: '53988516072',
    projectId: 'liad-apps',
    storageBucket: 'liad-apps.firebasestorage.app',
    iosBundleId: 'com.example.liad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB49uGHkrNM35Pp_w7NsWkB7vnLNwEJ8F8',
    appId: '1:53988516072:web:fdf6f59c20f32172d1e95d',
    messagingSenderId: '53988516072',
    projectId: 'liad-apps',
    authDomain: 'liad-apps.firebaseapp.com',
    storageBucket: 'liad-apps.firebasestorage.app',
  );
}
